# 1.5.4 navigation/filter UX overhaul.
def _replace_between(text, start, end, replacement):
    a = text.index(start)
    b = text.index(end, a)
    return text[:a] + replacement + text[b:]

appjs = root / "app/src/main/assets/app.js"
ux = appjs.read_text()
ux = ux.replace(
    '>Сочетания</button>',
    '>Каталог</button>',
    1,
)
ux = _replace_between(ux, "function filtered(base=D)", "function card(p)", r'''function filtered(base=D){const q=state.query.trim().toLowerCase();return base.filter(p=>{if(state.volume&&p.volume!==state.volume)return false;if(state.count){if(state.count==='6+'){if(p.colors.length<6)return false}else if(p.colors.length!==Number(state.count))return false}if(state.category){const i=allInfo.get(p.id);if(![i.temp,i.contrast,i.chroma,i.light].includes(state.category))return false}if(q){const inf=allInfo.get(p.id);const hay=[String(p.number),number(p),inf.temp,inf.contrast,inf.chroma,inf.light,...p.colors.flatMap(c=>[c.name,c.ru,c.hex,c.wadaId||''])].join(' ').toLowerCase();if(!hay.includes(q))return false}return true})}
const hasFilters=()=>Boolean(state.query.trim()||state.volume||state.count||state.category);
const countLabel=v=>!v?'Любое количество':v==='6+'?'6+ цветов':`${v} ${colorWord(Number(v))}`;
const filterSummary=()=>{const a=[];if(state.volume)a.push(`Том ${state.volume===1?'I':'II'}`);if(state.count)a.push(countLabel(state.count));if(state.category)a.push(state.category);return a.join(' · ')};
''')
ux = _replace_between(ux, "function catalog(base=D)", "const cats=", r'''function catalog(base=D){const list=filtered(base),shown=list.slice(0,state.limit),active=hasFilters();return `${mast()}<main class="content page"><div class="search-wrap"><label class="sr-only" for="search">Поиск сочетаний</label><input id="search" class="search" inputmode="search" autocomplete="off" spellcheck="false" aria-label="Поиск по номеру, цвету, HEX или категории" placeholder="Номер, цвет, HEX или категория" value="${esc(state.query)}"><button class="clear-btn" id="clear" aria-label="Очистить поиск">×</button></div>
<section class="filter-panel" aria-label="Фильтры каталога"><div class="filter-panel-head"><div><strong>Фильтры каталога</strong><span>Том и количество цветов</span></div><button class="reset-filters" id="resetFilters" ${active?'':'disabled'}>Сбросить всё</button></div>
<div class="filter-group"><div class="filter-label">Том</div><div class="filter-options" role="group" aria-label="Том"><button class="chip ${state.volume===0?'active':''}" data-vol="0" aria-pressed="${state.volume===0}">Оба тома</button><button class="chip ${state.volume===1?'active':''}" data-vol="1" aria-pressed="${state.volume===1}">Том I</button><button class="chip ${state.volume===2?'active':''}" data-vol="2" aria-pressed="${state.volume===2}">Том II</button></div></div>
<div class="filter-group"><div class="filter-label">Количество цветов</div><div class="filter-options" role="group" aria-label="Количество цветов"><button class="chip ${state.count===0?'active':''}" data-count="0" aria-pressed="${state.count===0}">Любое</button><button class="chip ${state.count===2?'active':''}" data-count="2" aria-pressed="${state.count===2}">2</button><button class="chip ${state.count===3?'active':''}" data-count="3" aria-pressed="${state.count===3}">3</button><button class="chip ${state.count===4?'active':''}" data-count="4" aria-pressed="${state.count===4}">4</button><button class="chip ${state.count===5?'active':''}" data-count="5" aria-pressed="${state.count===5}">5</button><button class="chip ${state.count==='6+'?'active':''}" data-count="6+" aria-pressed="${state.count==='6+'}">6+</button></div></div>
${state.category?`<div class="category-context"><div><span>Тематическая категория</span><strong>${esc(state.category)}</strong></div><button id="clearCategory">Снять</button></div>`:''}</section>
<div class="section-meta"><strong>${list.length} из ${base.length===D.length?581:base.length}</strong><span>${filterSummary()||'все сочетания'}</span></div>${list.length?`<div class="grid">${shown.map(card).join('')}</div>${shown.length<list.length?`<button class="load-more" id="more">Показать ещё · ${list.length-shown.length}</button>`:''}`:`<div class="empty"><div class="empty-art" aria-hidden="true"><i class="e1"></i><i class="e2"></i><i class="e3"></i></div><h2>Ничего не найдено</h2><p>Измените условия или нажмите «Сбросить всё».</p></div>`}</main>${bottom()}`}
''')
ux = _replace_between(ux, "const cats=", "function favorites()", r'''const cats=()=>{const defs=[['Тёплые','Температура'],['Холодные','Температура'],['Смешанные','Температура'],['Светлые','Светлота'],['Средние','Светлота'],['Тёмные','Светлота'],['Насыщенные','Насыщенность'],['Умеренные','Насыщенность'],['Приглушённые','Насыщенность'],['Высокий контраст','Контраст'],['Средний контраст','Контраст'],['Низкий контраст','Контраст']];return defs.map((d,k)=>{const n=D.filter(p=>{const i=allInfo.get(p.id);return [i.temp,i.contrast,i.chroma,i.light].includes(d[0])}).length;const pal=D[(k*37+12)%D.length].colors;return{name:d[0],group:d[1],n,colors:[pal[0]?.hex||'#c66b3a',pal[1]?.hex||'#6c7890',pal[2]?.hex||'#c8b26d']}})};
function categoryCard(c){const on=state.category===c.name;return `<button class="cat ${on?'active':''}" data-val="${esc(c.name)}" aria-label="${esc(c.name)}: ${c.n} ${paletteWord(c.n)}" aria-pressed="${on}" style="--c1:${c.colors[0]};--c2:${c.colors[1]};--c3:${c.colors[2]}"><span class="cat-arrow" aria-hidden="true">${on?'✓':'↗'M</span><div class="glyph" aria-hidden="true"><i class="g g1"></i><i class="g g2"></i><i class="g g3"></i></div><div class="cat-name">${esc(c.name)}</div><div class="cat-count">${c.n} ПАЛИТР</div></button>`}
function categories(){const all=cats(),groups=['Температура','Светлота','Насыщенность','Контраст'],catalogBits=[];if(state.volume)catalogBits.push(`Том ${state.volume===1?'I':'II'}`);if(state.count)catalogBits.push(countLabel(state.count));return `${mast()}<main class="content page"><h2 class="page-title">Тематические категории</h2><p class="page-lead">Здесь только смысловые признаки палитр. Том и количество цветов настраиваются отдельно в «Каталоге», поэтому разделы больше не дублируют друг друга.</p>${catalogBits.length?`<div class="catalog-filter-note"><div><span>Фильтры каталога сохраняются</span><strong>${esc(catalogBits.join(' · '))}</strong></div><button id="clearCatalogFiltersHere">Сбросить</button></div>`:''}${state.category?`<div class="category-current"><div><span>Сейчас выбрано</span><strong>${esc(state.category)}</strong></div><div class="category-current-actions"><button id="goCatalog">Показать в каталоге</button><button id="clearCategoryHere">Сбросить</button></div></div>`:''}${groups.map(g=>`<section class="cat-section"><div class="cat-section-head"><h3>${g}</h3></div><div class="cat-grid">${all.filter(c=>c.group===g).map(categoryCard).join('')}</div></section>`).join('')}</main>${bottom()}`}
''')
ux = ux.replace(
    "function setTab(tab){state.tab=tab;state.detail=null;state.overlay=null;state.limit=48;state.category=null;render();window.scrollTo(0,0)}",
    "function setTab(tab){state.tab=tab;state.detail=null;state.overlay=null;state.limit=48;render();window.scrollTo(0,0)}",
)
ux = _replace_between(ux, "function bind(){", "window.__wadaruBack=", r'''function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav)});document.querySelectorAll('[data-open]').forEach(e=>{const open=()=>{state.detail=e.dataset.open;render()};e.onclick=open;e.onkeydown=ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();open()}}});document.querySelectorAll('[data-vol]').forEach(b=>b.onclick=()=>{state.volume=+b.dataset.vol;state.limit=48;render(false)});document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{const raw=b.dataset.count;state.count=raw==='6+'?'6+':Number(raw);state.limit=48;render(false)});const s=$('#search');if(s)s.oninput=e=>{state.query=e.target.value;state.limit=48;const v=e.target.value;render(false);const ns=$('#search');if(ns){ns.focus();try{ns.setSelectionRange(v.length,v.length)}catch(_){}}};const cl=$('#clear');if(cl)cl.onclick=()=>{state.query='';render(false);$('#search')?.focus()};$('#resetFilters')?.addEventListener('click',()=>{state.query='';state.volume=0;state.count=0;state.category=null;state.limit=48;render(false)});$('#clearCategory')?.addEventListener('click',()=>{state.category=null;state.limit=48;render(false)});$('#clearCategoryHere')?.addEventListener('click',()=>{state.category=null;render(false)});$('#clearCatalogFiltersHere')?.addEventListener('click',()=>{state.volume=0;state.count=0;render(false)});$('#goCatalog')?.addEventListener('click',()=>setTab('catalog'));$('#more')?.addEventListener('click',()=>{state.limit+=48;render(false)});document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{state.query='';state.category=b.dataset.val;state.tab='catalog';state.limit=48;render();window.scrollTo(0,0)});$('#back')?.addEventListener('click',()=>{state.detail=null;render()});$('#aboutBtn')?.addEventListener('click',()=>{state.overlay='about';render()});$('#overlayBack')?.addEventListener('click',()=>{state.overlay=null;render()});document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{const t=b.dataset.copy;let ok=false;try{ok=copyFallback(t)}catch(_){ok=false}toast(ok?`${t} скопирован`:`${t}`)})}
''')
back_start = ux.index("window.__wadaruBack=")
back_end = ux.index("\nif(D.length", back_start)
ux = ux[:back_start] + "window.__wadaruBack=()=>{if(state.overlay){state.overlay=null;render();return true}if(state.detail){state.detail=null;render();return true}if(state.tab!=='catalog'){setTab('catalog');return true}return false};" + ux[back_end:]
ux = ux.replace("Версия 1.5.0.", "Версия 1.5.4.").replace("Версия 1.5.1.", "Версия 1.5.4.").replace("Версия 1.5.2.", "Версия 1.5.4.").replace("Версия 1.5.3.", "Версия 1.5.4.")
appjs.write_text(ux)

index = root / "app/src/main/assets/index.html"
html = index.read_text()
ux_css = r'''
/* 1.5.4: stable, explicit catalog filters and category navigation */
.filter-panel{margin:2px 0 15px;padding:15px 14px 14px;border:1px solid #34312d;background:#171613;border-radius:22px 18px 24px 19px}
.filter-panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:14px}
.filter-panel-head>div{display:flex;flex-direction:column;gap:3px}.filter-panel-head strong{font-size:14px;color:#e5ddd0}.filter-panel-head span{font-size:11px;color:#817c75}
.reset-filters{border:0;background:transparent;color:#c5b6d9;font-size:12px;padding:3px 0 5px 10px}.reset-filters:disabled{color:#595650;opacity:.7}
.filter-group+.filter-group{margin-top:13px;padding-top:13px;border-top:1px solid #292722}.filter-label{font-size:11px;letter-spacing:.08em;text-transform:uppercase;color:#8e887f;margin:0 0 8px 2px}.filter-options{display:flex;flex-wrap:wrap;gap:8px;overflow:visible}.filter-options .chip{min-width:0;margin:0;padding:9px 13px}.filter-options .chip.active{transform:none}
.category-context{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:14px;padding:12px 12px 11px;background:#201d22;border:1px solid #4b4357;border-radius:16px 19px 15px 18px}.category-context>div{display:flex;flex-direction:column;gap:2px;min-width:0}.category-context span{font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:#9d94a8}.category-context strong{font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.category-context button{border:0;background:#5a5269;color:#f2ebdf;padding:8px 11px;border-radius:12px 15px 11px 14px;font-size:12px;flex:0 0 auto}
.section-meta span{max-width:62%;text-align:right;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.cat-section{margin:27px 0 0}.cat-section:first-of-type{margin-top:20px}.cat-section-head{display:flex;align-items:center;justify-content:space-between;margin:0 3px 10px}.cat-section-head h3{margin:0;font-size:11px;letter-spacing:.15em;text-transform:uppercase;color:#aaa294;font-weight:650}.cat.active{border-color:#746a83;background:#211f24;box-shadow:inset 0 0 0 1px rgba(166,155,191,.12)}.cat.active .cat-arrow{color:#ded3ee}.category-current{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:18px 0 4px;padding:13px 14px;background:#201d22;border:1px solid #4b4357;border-radius:18px 15px 20px 16px}.category-current>div:first-child{display:flex;flex-direction:column;gap:2px}.category-current span{font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:#9c94a7}.category-current strong{font-size:15px}.category-current-actions{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.category-current button{border:1px solid #5b5366;background:#29252f;color:#e8e0ee;padding:7px 10px;border-radius:11px 14px 10px 13px;font-size:11px}.category-current button:last-child{background:transparent;color:#aaa19a;border-color:#413d3a}
.cat{display:flex;flex-direction:column;align-items:stretch}.cat .glyph{flex:0 0 auto}.cat-name{margin-top:auto;padding-top:1px}.cat-count{position:static;margin-top:5px;font-size:11px;line-height:1.2;text-align:left}
.catalog-filter-note{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:18px 0 4px;padding:12px 14px;background:#18171a;border:1px solid #3d3942;border-radius:17px 20px 16px 19px}.catalog-filter-note>div{display:flex;flex-direction:column;gap:2px;min-width:0}.catalog-filter-note span{font-size:10px;letter-spacing:.09em;text-transform:uppercase;color:#8d8791}.catalog-filter-note strong{font-size:14px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.catalog-filter-note button{border:1px solid #45404a;background:transparent;color:#b3aab8;padding:7px 10px;border-radius:11px 14px 10px 13px;font-size:11px;flex:0 0 auto}
@media(max-width:420px){.filter-panel{padding-left:12px;padding-right:12px}.filter-options{gap:7px}.filter-options .chip{padding:9px 11px}.category-current{align-items:flex-start;flex-direction:column}.category-current-actions{justify-content:flex-start}}
'''
html = html.replace("\n</style>", ux_css + "\n</style>", 1)
index.write_text(html)

assert "Фильтры каталога" in ux
assert "Тематические категории" in ux
assert "Фильтры каталога сохраняются" in ux
assert "state.category=null;render();window.scrollTo" not in ux
assert "class=\"filters\"" not in ux
