from pathlib import Path
import re,sys
root=Path(sys.argv[1] if len(sys.argv)>1 else "project")
app=root/"app/src/main/assets/app.js"
idx=root/"app/src/main/assets/index.html"
s=app.read_text(encoding='utf-8')

def between(text,start,end,repl):
    a=text.index(start); b=text.index(end,a)
    return text[:a]+repl+text[b:]

# state/theme
s=s.replace("let state={tab:'catalog',query:'',volume:0,count:0,category:null,detail:null,overlay:null,limit:48};\nlet fav=new Set(loadJson('wada-favorites',[]));",
"const savedTheme=loadJson('wada-theme','dark');\nlet state={tab:'catalog',query:'',volume:0,count:0,category:null,detail:null,overlay:null,limit:48,filtersOpen:false,categoryScroll:0,theme:savedTheme==='light'?'light':'dark'};\nlet fav=new Set(loadJson('wada-favorites',[]));\nfunction applyTheme(){document.documentElement.dataset.theme=state.theme;const m=document.querySelector('meta[name=\\\"theme-color\\\"]');if(m)m.setAttribute('content',state.theme==='light'?'#f2eee4':'#151511')}\nfunction saveTheme(){try{localStorage.setItem('wada-theme',JSON.stringify(state.theme))}catch(_){}applyTheme()}")

# paint: exact, deterministic use of every palette color
s=re.sub(r"function paintHTML\(p\)\{.*?\}\nfunction heart", "function paintHTML(p){const colors=p.colors.map(c=>c.hex);return `<span class=\\\"paint-grid\\\" data-count=\\\"${colors.length}\\\">${colors.map((hex,i)=>`<i class=\\\"paint\\\" aria-hidden=\\\"true\\\" data-index=\\\"${i}\\\" style=\\\"background:${hex}\\\"></i>`).join('')}</span>`}\nfunction heart", s, count=1)

# mast removes info icon
s=re.sub(r"function mast\(\)\{return `.*?`\}\nfunction bottom", "function mast(){return `<header class=\\\"mast\\\"><div class=\\\"brand\\\"><div class=\\\"brand-kicker\\\">SANZŌ WADA · ЦВЕТОВАЯ КОМПОЗИЦИЯ</div><h1>Цвета Вада</h1><p>581 сочетание · два тома · полностью офлайн</p></div><div class=\\\"art-mark\\\" aria-hidden=\\\"true\\\"><i class=\\\"s a\\\"></i><i class=\\\"s b\\\"></i><i class=\\\"s c\\\"></i><i class=\\\"s d\\\"></i><i class=\\\"line\\\"></i></div></header>`}\nfunction bottom", s, count=1, flags=re.S)

bottom=r'''function bottom(){const filterOn=state.tab==='catalog';return `<nav class="bottom" aria-label="Основная навигация">
<button class="navbtn ${filterOn?'active':''}" id="filtersNav" aria-label="Открыть фильтры каталога" ${filterOn?'aria-current="page"':''}><span class="navicon"><svg aria-hidden="true" viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="1.9" stroke-linecap="round"><path d="M5 7h18M8 14h12M11 21h6"/><circle cx="10" cy="7" r="2" fill="currentColor" stroke="none"/><circle cx="17" cy="14" r="2" fill="currentColor" stroke="none"/><circle cx="14" cy="21" r="2" fill="currentColor" stroke="none"/></svg>${hasFilters()?`<b class="nav-badge">${[state.volume,state.count,state.category].filter(Boolean).length}</b>`:''}</span>Фильтры</button>
<button class="navbtn ${state.tab==='favorites'?'active':''}" data-tab="favorites" ${state.tab==='favorites'?'aria-current="page"':''}><span class="navicon"><svg aria-hidden="true" viewBox="0 0 28 28" fill="currentColor"><path d="M14 24C10.7 20.9 4 17 4 11.4 4 7.9 6.5 5.5 9.5 5.5c2 0 3.6 1.1 4.5 2.6.9-1.5 2.6-2.6 4.5-2.6 3.1 0 5.5 2.4 5.5 5.9C24 17 17.3 20.9 14 24Z"/></svg></span>Избранное</button>
<button class="navbtn ${state.tab==='settings'?'active':''}" data-tab="settings" ${state.tab==='settings'?'aria-current="page"':''}><span class="navicon"><svg aria-hidden="true" viewBox="0 0 28 28" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="14" cy="14" r="4"/><path d="M14 3.5v3M14 21.5v3M3.5 14h3M21.5 14h3M6.6 6.6l2.1 2.1M19.3 19.3l2.1 2.1M21.4 6.6l-2.1 2.1M8.7 19.3l-2.1 2.1"/></svg></span>Настройки</button>
</nav>`}'''
s=between(s,"function bottom()","function filtered",bottom+"\n")

# helpers after filterSummary
insert="""
function activeFilterBar(){const bits=[];if(state.volume)bits.push(`Том ${state.volume===1?'I':'II'}`);if(state.count)bits.push(countLabel(state.count));if(state.category)bits.push(state.category);return bits.length?`<div class=\"active-filter-bar\"><div class=\"active-filter-pills\">${bits.map(x=>`<span>${esc(x)}</span>`).join('')}</div><button id=\"resetFiltersCompact\">Сбросить</button></div>`:''}
function filterSheet(){const all=cats();return `<div class=\"sheet-backdrop\" id=\"filterBackdrop\"></div><section class=\"filter-sheet\" role=\"dialog\" aria-modal=\"true\" aria-label=\"Фильтры каталога\"><div class=\"sheet-handle\" aria-hidden=\"true\"></div><div class=\"sheet-head\"><div><strong>Фильтры каталога</strong><span>${filterSummary()||'Все сочетания'}</span></div><div class=\"sheet-head-actions\"><button id=\"resetFilters\" ${hasFilters()?'':'disabled'}>Сбросить</button><button id=\"closeFilters\" aria-label=\"Закрыть фильтры\">×</button></div></div><div class=\"sheet-group\"><div class=\"sheet-label\">Том</div><div class=\"sheet-options\"><button class=\"chip ${state.volume===0?'active':''}\" data-vol=\"0\">Оба тома</button><button class=\"chip ${state.volume===1?'active':''}\" data-vol=\"1\">Том I</button><button class=\"chip ${state.volume===2?'active':''}\" data-vol=\"2\">Том II</button></div></div><div class=\"sheet-group\"><div class=\"sheet-label\">Количество цветов</div><div class=\"sheet-options\"><button class=\"chip ${state.count===0?'active':''}\" data-count=\"0\">Любое</button><button class=\"chip ${state.count===2?'active':''}\" data-count=\"2\">2</button><button class=\"chip ${state.count===3?'active':''}\" data-count=\"3\">3</button><button class=\"chip ${state.count===4?'active':''}\" data-count=\"4\">4</button><button class=\"chip ${state.count===5?'active':''}\" data-count=\"5\">5</button><button class=\"chip ${state.count==='6+'?'active':''}\" data-count=\"6+\">6+</button></div></div><div class=\"sheet-group\"><div class=\"sheet-label\">Категория <span>прокручивается отдельно</span></div><div class=\"category-scroll\" id=\"categoryScroll\"><button class=\"category-chip ${!state.category?'active':''}\" data-category=\"\">Все</button>${all.map(c=>`<button class=\"category-chip ${state.category===c.name?'active':''}\" data-category=\"${esc(c.name)}\"><b>${esc(c.name)}</b><small>${c.group}</small></button>`).join('')}</div></div></section>`}
"""
s=s.replace("const filterSummary=()=>{const a=[];if(state.volume)a.push(`Том ${state.volume===1?'I':'II'}`);if(state.count)a.push(countLabel(state.count));if(state.category)a.push(state.category);return a.join(' · ')};",
"const filterSummary=()=>{const a=[];if(state.volume)a.push(`Том ${state.volume===1?'I':'II'}`);if(state.count)a.push(countLabel(state.count));if(state.category)a.push(state.category);return a.join(' · ')};"+insert)

# catalog; no expanded filter panel
catalog=r'''function catalog(base=D){const list=filtered(base),shown=list.slice(0,state.limit);return `${mast()}<main class="content page"><div class="search-wrap"><label class="sr-only" for="search">Поиск сочетаний</label><input id="search" class="search" inputmode="search" autocomplete="off" spellcheck="false" aria-label="Поиск по номеру, цвету, HEX или категории" placeholder="Номер, цвет, HEX или категория" value="${esc(state.query)}"><button class="clear-btn" id="clear" aria-label="Очистить поиск">×</button></div>${activeFilterBar()}<div class="section-meta"><strong>${list.length} из ${base.length===D.length?581:base.length}</strong><span>${filterSummary()||'все сочетания'}</span></div>${list.length?`<div class="grid">${shown.map(card).join('')}</div>${shown.length<list.length?`<button class="load-more" id="more">Показать ещё · ${list.length-shown.length}</button>`:''}`:`<div class="empty"><div class="empty-art" aria-hidden="true"><i class="e1"></i><i class="e2"></i><i class="e3"></i></div><h2>Ничего не найдено</h2><p>Откройте фильтры снизу или сбросьте активные условия.</p></div>`}</main>${bottom()}${state.filtersOpen?filterSheet():''}`}'''
s=between(s,"function catalog(base=D)","const cats=",catalog+"\n")

# Keep cats, delete categoryCard/categories between them and favorites by replacement
start=s.index("function categoryCard")
end=s.index("function favorites",start)
s=s[:start]+s[end:]

# settings before descriptions
settings=r'''function settings(){return `${mast()}<main class="content page settings-page"><h2 class="page-title">Настройки</h2><p class="page-lead">Внешний вид и информация о приложении.</p><section class="settings-card"><div class="settings-row"><div><strong>Тема</strong><span>Выберите оформление интерфейса</span></div></div><div class="theme-choice" role="group" aria-label="Тема"><button data-theme-choice="dark" class="${state.theme==='dark'?'active':''}">Тёмная</button><button data-theme-choice="light" class="${state.theme==='light'?'active':''}">Светлая</button></div></section><button class="settings-link" id="openAbout"><span class="settings-info-icon">i</span><span><strong>О приложении</strong><small>Версия, конфиденциальность, источники и права</small></span><b>›</b></button></main>${bottom()}`}'''
pos=s.index("function descriptions")
s=s[:pos]+settings+"\n"+s[pos:]

# about version
s=s.replace('Версия 1.5.4.','Версия 1.5.5.')

# render/setTab/bind/back replacement
render_block=r'''function render(scrollTop=true){const app=$('#app');if(!app)return;applyTheme();document.body.classList.toggle('sheet-open',state.filtersOpen);if(state.overlay==='about'){app.innerHTML=about();bind();if(scrollTop)window.scrollTo(0,0);return}if(state.detail){const p=D.find(x=>x.id===state.detail);if(p){app.innerHTML=detail(p);bind();if(scrollTop)window.scrollTo(0,0);return}state.detail=null}app.innerHTML=state.tab==='favorites'?favorites():state.tab==='settings'?settings():catalog();bind();if(state.query){const c=$('#clear');if(c)c.style.display='block'}if(state.filtersOpen){const sc=$('#categoryScroll');if(sc){sc.scrollLeft=state.categoryScroll;sc.onscroll=()=>{state.categoryScroll=sc.scrollLeft}}}}
function setTab(tab){state.tab=tab;state.detail=null;state.overlay=null;state.filtersOpen=false;state.limit=48;render();window.scrollTo(0,0)}
function openFilters(){state.tab='catalog';state.detail=null;state.overlay=null;state.filtersOpen=true;render(false)}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('#filtersNav')?.addEventListener('click',()=>{if(state.tab!=='catalog'||!state.filtersOpen)openFilters();else{state.filtersOpen=false;render(false)}});document.querySelectorAll('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav)});document.querySelectorAll('[data-open]').forEach(e=>{const open=()=>{state.detail=e.dataset.open;state.filtersOpen=false;render()};e.onclick=open;e.onkeydown=ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();open()}}});document.querySelectorAll('[data-vol]').forEach(b=>b.onclick=()=>{state.volume=+b.dataset.vol;state.limit=48;render(false)});document.querySelectorAll('[data-count]').forEach(b=>b.onclick=()=>{const raw=b.dataset.count;state.count=raw==='6+'?'6+':Number(raw);state.limit=48;render(false)});document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{const sc=$('#categoryScroll');if(sc)state.categoryScroll=sc.scrollLeft;state.category=b.dataset.category||null;state.limit=48;render(false)});const q=$('#search');if(q)q.oninput=e=>{state.query=e.target.value;state.limit=48;const v=e.target.value;render(false);const ns=$('#search');if(ns){ns.focus();try{ns.setSelectionRange(v.length,v.length)}catch(_){}}};$('#clear')?.addEventListener('click',()=>{state.query='';render(false);$('#search')?.focus()});const reset=()=>{state.query='';state.volume=0;state.count=0;state.category=null;state.categoryScroll=0;state.limit=48;render(false)};$('#resetFilters')?.addEventListener('click',reset);$('#resetFiltersCompact')?.addEventListener('click',reset);$('#closeFilters')?.addEventListener('click',()=>{state.filtersOpen=false;render(false)});$('#filterBackdrop')?.addEventListener('click',()=>{state.filtersOpen=false;render(false)});$('#more')?.addEventListener('click',()=>{state.limit+=48;render(false)});$('#back')?.addEventListener('click',()=>{state.detail=null;render()});$('#openAbout')?.addEventListener('click',()=>{state.overlay='about';state.filtersOpen=false;render()});$('#overlayBack')?.addEventListener('click',()=>{state.overlay=null;render()});document.querySelectorAll('[data-theme-choice]').forEach(b=>b.onclick=()=>{state.theme=b.dataset.themeChoice==='light'?'light':'dark';saveTheme();render(false)});document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{const t=b.dataset.copy;let ok=false;try{ok=copyFallback(t)}catch(_){ok=false}toast(ok?`${t} скопирован`:`${t}`)})}
window.__wadaruBack=()=>{if(state.filtersOpen){state.filtersOpen=false;render(false);return true}if(state.overlay){state.overlay=null;render();return true}if(state.detail){state.detail=null;render();return true}if(state.tab!=='catalog'){setTab('catalog');return true}return false};'''
s=between(s,"function render(scrollTop=true)","if(D.length!==581)",render_block+"\n")

# version in any remaining text
s=s.replace('Версия 1.5.4.','Версия 1.5.5.')
app.write_text(s,encoding='utf-8')

# CSS append
html=idx.read_text(encoding='utf-8')
css=r'''
/* 1.5.5 — exact palette covers, compact filters, settings and themes */
.palette-art,.hero-palette{position:relative;overflow:hidden}
.paint-grid{position:absolute;inset:0;display:flex;width:100%;height:100%;overflow:hidden}
.paint-grid .paint,.hero-palette .paint-grid .paint{position:relative!important;inset:auto!important;display:block;flex:1 1 0;min-width:0;height:100%;clip-path:none!important;opacity:1!important;transform:none!important;z-index:auto!important}
.paint-grid .paint+.paint{box-shadow:inset 1px 0 rgba(255,255,255,.08)}
.hero-palette .paint-grid{inset:0!important}
.mast .about-btn{display:none!important}
.active-filter-bar{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:-3px 0 14px;padding:9px 10px 9px 11px;background:var(--panel);border:1px solid var(--line);border-radius:15px 18px 14px 17px}
.active-filter-pills{display:flex;gap:6px;overflow:auto;scrollbar-width:none;min-width:0}.active-filter-pills::-webkit-scrollbar{display:none}.active-filter-pills span{flex:0 0 auto;padding:5px 8px;border-radius:9px 11px 8px 10px;background:var(--panel2);color:var(--paper);font-size:11px;white-space:nowrap}.active-filter-bar button{border:0;background:transparent;color:var(--accent);font-size:11px;flex:0 0 auto}
.sheet-open{overflow:hidden}.sheet-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.52);z-index:79;backdrop-filter:blur(2px)}
.filter-sheet{position:fixed;left:0;right:0;bottom:0;z-index:80;max-height:min(73vh,690px);overflow-y:auto;padding:8px 16px calc(92px + env(safe-area-inset-bottom));background:var(--panel);border-top:1px solid var(--line);border-radius:25px 25px 0 0;box-shadow:0 -18px 50px rgba(0,0,0,.32);animation:sheetUp .2s ease-out}
@keyframes sheetUp{from{transform:translateY(18px);opacity:.7}to{transform:none;opacity:1}}
.sheet-handle{width:44px;height:4px;border-radius:8px;background:var(--muted);opacity:.45;margin:0 auto 14px}.sheet-head{display:flex;justify-content:space-between;align-items:flex-start;gap:12px;margin-bottom:16px}.sheet-head>div:first-child{display:flex;flex-direction:column;gap:3px}.sheet-head strong{font-size:18px}.sheet-head span{font-size:11px;color:var(--muted)}.sheet-head-actions{display:flex;align-items:center;gap:8px}.sheet-head-actions button{border:0;background:transparent;color:var(--accent);font-size:12px;padding:6px}.sheet-head-actions button:disabled{opacity:.35}.sheet-head-actions #closeFilters{font-size:25px;color:var(--muted);line-height:1}
.sheet-group{padding:14px 0;border-top:1px solid var(--line)}.sheet-label{font-size:11px;text-transform:uppercase;letter-spacing:.09em;color:var(--muted);margin:0 0 9px 2px}.sheet-label span{font-size:9px;text-transform:none;letter-spacing:0;margin-left:5px;opacity:.8}.sheet-options{display:flex;flex-wrap:wrap;gap:8px}.sheet-options .chip{margin:0;padding:9px 13px;min-width:0}.sheet-options .chip.active{transform:none}
.category-scroll{display:flex;gap:8px;overflow-x:auto;overscroll-behavior-inline:contain;scroll-snap-type:x proximity;padding:1px 2px 8px;margin:0 -2px;scrollbar-width:none}.category-scroll::-webkit-scrollbar{display:none}.category-chip{flex:0 0 auto;min-width:108px;max-width:160px;border:1px solid var(--line);background:var(--bg2);color:var(--paper);padding:10px 12px;border-radius:14px 18px 13px 16px;text-align:left;scroll-snap-align:start}.category-chip b{display:block;font-size:12px;white-space:nowrap}.category-chip small{display:block;margin-top:3px;color:var(--muted);font-size:9px}.category-chip.active{background:#5d566d;border-color:#756a86;color:#fff}.category-chip.active small{color:#ddd2e8}
.nav-badge{position:absolute;right:2px;top:-4px;min-width:16px;height:16px;padding:0 4px;border-radius:9px;background:#d59b48;color:#1a1712;font-size:9px;display:grid;place-items:center}.navicon{position:relative}
.settings-page{max-width:720px}.settings-card{margin-top:20px;padding:17px;background:var(--panel);border:1px solid var(--line);border-radius:22px 17px 25px 19px}.settings-row strong{display:block;font-size:16px}.settings-row span{display:block;margin-top:4px;color:var(--muted);font-size:12px}.theme-choice{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.theme-choice button{border:1px solid var(--line);background:var(--bg2);color:var(--paper);padding:12px;border-radius:14px 18px 13px 16px}.theme-choice button.active{background:#5d566d;border-color:#756a86;color:#fff}.settings-link{width:100%;margin-top:12px;border:1px solid var(--line);background:var(--panel);color:var(--paper);padding:14px 15px;border-radius:18px 22px 17px 20px;display:grid;grid-template-columns:38px 1fr auto;gap:12px;align-items:center;text-align:left}.settings-info-icon{width:34px;height:34px;border:1px solid var(--muted);border-radius:50%;display:grid;place-items:center;font:italic 20px Georgia,serif}.settings-link span:nth-child(2){display:flex;flex-direction:column;gap:3px}.settings-link small{color:var(--muted);font-size:10px}.settings-link>b{font-size:24px;color:var(--muted);font-weight:400}
html[data-theme="light"]{color-scheme:light;--bg:#f2eee4;--bg2:#e9e2d6;--paper:#292722;--muted:#716c63;--line:#cfc6b8;--panel:#faf7ef;--panel2:#e7dfd2;--accent:#655b78;--accent2:#9b672b;--nav:#eee8de}
html[data-theme="light"] body:before{opacity:.1;mix-blend-mode:multiply}html[data-theme="light"] .mast{background:#e9e2d6;border-color:#cfc6b8}html[data-theme="light"] .brand-kicker{color:#756c60}html[data-theme="light"] .brand p{color:#756f66}html[data-theme="light"] .search{background:#faf7ef;border-color:#c9c0b4;color:#292722}html[data-theme="light"] .search:focus{background:#fffdf8;border-color:#81758f}html[data-theme="light"] .card{background:#fbf8f2;border-color:#d9d0c4;box-shadow:0 9px 24px rgba(70,55,38,.08)}html[data-theme="light"] .card:active{background:#f3eee6}html[data-theme="light"] .card-id,html[data-theme="light"] .card-en,html[data-theme="light"] .card-tags{color:#766f66}html[data-theme="light"] .card-id b,html[data-theme="light"] .card-names{color:#2b2925}html[data-theme="light"] .bottom{background:rgba(239,233,224,.97);border-color:#cfc6b8}html[data-theme="light"] .navbtn{color:#756f7d}html[data-theme="light"] .navbtn.active{color:#2d2932}html[data-theme="light"] .navbtn.active .navicon{background:#cfc5dd;color:#382f45}html[data-theme="light"] .detail-top{background:#e9e2d6;border-color:#cfc6b8}html[data-theme="light"] .detail-section{border-color:#d6cec1}html[data-theme="light"] .detail-section p{color:#3a3732}html[data-theme="light"] .detail-sub,html[data-theme="light"] .source-note,html[data-theme="light"] .cen{color:#756f66!important}html[data-theme="light"] .detail-chips span,html[data-theme="light"] .hex{background:#eae2d6;border-color:#c8beb0;color:#423e38}html[data-theme="light"] .color-row{border-color:#d6cec1}html[data-theme="light"] .legal-page{background:var(--bg)}html[data-theme="light"] .legal-wrap p{color:#3b3833}html[data-theme="light"] .legal-wrap section{border-color:#d3cabc}html[data-theme="light"] .legal-wrap code{background:#e2d9cc;color:#51485c}
@media(max-width:420px){.filter-sheet{padding-left:13px;padding-right:13px}.category-chip{min-width:104px}.settings-page{padding-left:15px;padding-right:15px}}
'''
html=html.replace('\n</style>',css+'\n</style>',1)
# color-scheme meta can remain dark; runtime data-theme/css controls actual rendering
idx.write_text(html,encoding='utf-8')

# sanity static checks
assert 'class="filters"' not in s
assert 'Категории</button>' not in s
assert 'about-btn' not in s.split('function mast()',1)[1].split('function bottom()',1)[0]
assert 'data-tab="settings"' in s
assert 'category-scroll' in s
assert 'paint-grid' in s
assert 'Версия 1.5.5.' in s
print('1.5.5 UX patch applied')