package com.dmitry.wadaru

object RussianColorNames {
    private val names = mapOf(
        "English Red" to "Английский красный",
        "Cerulian Blue" to "Церулеановый синий",
        "Yellow Orange" to "Жёлто-оранжевый",
        "Dark Tyrian Blue" to "Тёмный тирский синий",
        "Pale Lemon Yellow" to "Бледно-лимонный жёлтый",
        "Raw Sienna" to "Сырая сиена",
        "Isabella Color" to "Изабелловый",
        "Red Violet" to "Красно-фиолетовый",
        "Cossack Green" to "Казачий зелёный",
        "Vandar Poel's Blue" to "Синий Ван дер Пула",
        "Grenadine Pink" to "Гренадиново-розовый",
        "Deep Indigo" to "Глубокий индиго",
        "Glaucous Green" to "Сизо-зелёный",
        "Orange" to "Оранжевый",
        "Grayish Lavender - A" to "Серовато-лавандовый A",
        "Cinnamon Rufous" to "Корично-рыжий",
        "Dull Blue Violet" to "Приглушённый сине-фиолетовый",
        "Violet Red" to "Фиолетово-красный",
        "Dark Citrine" to "Тёмный цитриновый",
        "Ivory Buff" to "Палевый слоновой кости",
        "Mineral Gray" to "Минеральный серый",
        "Green Blue" to "Зелёно-синий",
        "Veronia Purple" to "Пурпурный «Верония»",
        "Naples Yellow" to "Неаполитанский жёлтый",
        "Spinel Red" to "Шпинельно-красный",
        "Benzol Green" to "Бензольный зелёный",
        "Pale King's Blue 2" to "Бледный королевский синий 2",
        "Vandyke Red" to "Красный Ван Дейка",
        "Sea Green" to "Морской зелёный",
        "Eugenia Red | B" to "Красный «Евгения» B",
        "Fawn" to "Палевый",
        "Dusky Madder Violet" to "Тёмный мареново-фиолетовый",
        "Night Green" to "Ночной зелёный",
        "Mars Brown Tobacco" to "Табачно-коричневый «Марс»",
        "Calamine Blue" to "Каламиновый голубой",
        "Laelia Pink" to "Розовый «Лелия»",
        "Yellow" to "Жёлтый",
        "Deep Lyons Blue" to "Глубокий лионский синий",
        "Cinnamon Buff" to "Светло-коричный",
        "Light Mauve" to "Светлый мальвовый",
        "Sepia" to "Сепия",
        "Nile Blue" to "Нильский голубой",
        "Etruscan Red" to "Этрусский красный",
        "Golden Yellow" to "Золотисто-жёлтый",
        "Pale Raw Umber" to "Светлая сырая умбра",
        "Corinthian Pink" to "Коринфский розовый",
        "Slate Color" to "Сланцевый",
        "Madder Brown" to "Мареново-коричневый",
        "Salvia Blue" to "Шалфейно-синий",
        "Krongbergs Green" to "Зелёный Кронгберга",
        "Pompeian Red" to "Помпейский красный",
        "Red Orange" to "Красно-оранжевый",
        "Ochraceous Salmon" to "Охристо-лососевый",
        "Neutral Gray" to "Нейтральный серый",
        "Eosine Pink" to "Эозиново-розовый",
        "Light Brown Drab" to "Светлый серо-коричневый",
        "Carmine Red" to "Карминово-красный",
        "Turquoise Green" to "Бирюзово-зелёный",
        "Sulphine Yellow" to "Сульфиново-жёлтый",
        "Brick Red" to "Кирпично-красный",
        "Diamine Green" to "Диаминовый зелёный",
        "Carmine" to "Карминовый",
        "Helvetia Blue" to "Гельветический синий",
        "Citron Yellow" to "Цитронно-жёлтый",
        "Vinaceous Tawny" to "Винно-рыжеватый",
        "Yellow Ocher" to "Жёлтая охра",
        "Violet" to "Фиолетовый",
        "Aconite Violet" to "Аконитово-фиолетовый",
        "Light Porcelain Green" to "Светлый фарфорово-зелёный",
        "Olympic Blue" to "Олимпийский синий",
        "Lemon Yellow" to "Лимонно-жёлтый",
        "Seashell Pink" to "Розовый морской раковины",
        "Black" to "Чёрный",
        "Grayish Lavender - B" to "Серовато-лавандовый B",
        "Rosolanc Purple" to "Пурпурный «Розоланк»",
        "Blue" to "Синий",
        "Sulphur Yellow" to "Серно-жёлтый",
        "Light Glaucous Blue" to "Светлый сизо-голубой",
        "White" to "Белый",
        "Old Rose" to "Старая роза",
        "Taupe Brown" to "Серо-коричневый тауп",
        "Hay's Russet" to "Рыжевато-коричневый Хэя",
        "Citrine" to "Цитриновый",
        "Light Green Yellow" to "Светлый жёлто-зелёный",
        "Cotinga Purple" to "Пурпурный котинги",
        "Vistoris Lake" to "Лак «Висторис»",
        "Dark Soft Violet" to "Тёмный мягкий фиолетовый",
        "Olive Ocher" to "Оливковая охра",
        "Olive Green" to "Оливково-зелёный",
        "Warm Gray" to "Тёплый серый",
        "Lincoln Green" to "Линкольнский зелёный",
        "Rainette Green" to "Зелёный «Ренет»",
        "Violet Blue" to "Фиолетово-синий",
        "Pinkish Cinnamon" to "Розовато-коричный",
        "Venice Green" to "Венецианский зелёный",
        "Olive Buff" to "Светло-оливковый",
        "Deep Slate Green" to "Глубокий сланцево-зелёный",
        "Antwarp Blue" to "Антверпенский синий",
        "Orange Rufous" to "Оранжево-рыжий",
        "Coral Red" to "Кораллово-красный",
        "Dusky Green" to "Тёмный приглушённый зелёный",
        "Dull Violet Black" to "Приглушённый фиолетово-чёрный",
        "Olive" to "Оливковый",
        "Buffy Citrine" to "Светлый цитриново-охристый",
        "Cameo Pink" to "Камейно-розовый",
        "Chromium Green" to "Хромовый зелёный",
        "Apricot Yellow" to "Абрикосово-жёлтый",
        "Light Grayish Olive" to "Светлый серовато-оливковый",
        "Blackish Olive" to "Черновато-оливковый",
        "Brown" to "Коричневый",
        "Vandyke Brown" to "Коричневый Ван Дейка",
        "Yellow Green" to "Жёлто-зелёный",
        "Orange Yellow" to "Оранжево-жёлтый",
        "Peach Red" to "Персиково-красный",
        "Blue Violet" to "Сине-фиолетовый",
        "Cream Yellow" to "Кремово-жёлтый",
        "Olive Yellow" to "Оливково-жёлтый",
        "Pale Burnt Lake" to "Бледный жжёный лак",
        "Pistachio Green" to "Фисташково-зелёный",
        "Khaki" to "Хаки",
        "Peacock Blue" to "Павлиний синий",
        "Dull Viridian Green" to "Приглушённый виридиановый зелёный",
        "Scarlet" to "Алый",
        "Hydrangea Red" to "Гортензиево-красный",
        "Lilac" to "Сиреневый",
        "Deep Grayish Olive" to "Глубокий серовато-оливковый",
        "Jasper Red" to "Яшмово-красный",
        "Cobalt Green" to "Кобальтовый зелёный",
        "Pansy Purple" to "Фиалково-пурпурный",
        "Dark Medici Blue" to "Тёмный синий Медичи",
        "Ecru" to "Экрю",
        "Hermosa Pink" to "Розовый «Эрмоса»",
        "Deep Violet / Plumbeous" to "Глубокий фиолетовый / свинцовый",
        "Deep Slate Olive" to "Глубокий сланцево-оливковый",
        "Green" to "Зелёный",
        "Burnt Sienna" to "Жжёная сиена",
        "Light Brownish Olive" to "Светлый коричневато-оливковый",
        "Ochre Red" to "Охристо-красный",
        "Vinaceous Cinnamon" to "Винно-коричный",
        "Sudan Brown" to "Суданский коричневый",
        "Apricot Orange" to "Абрикосово-оранжевый",
        "Orange Citrine" to "Оранжево-цитриновый",
        "Eupatorium Purple" to "Посконниково-пурпурный",
        "Pomegranite Purple" to "Гранатово-пурпурный",
        "Dark Slate Purple" to "Тёмный сланцево-пурпурный",
        "Purple Drab" to "Тусклый пурпурно-серый",
        "Pyrite Yellow" to "Пиритово-жёлтый",
        "Fresh Color" to "Свежий телесно-коралловый",
        "Andover Green" to "Андоверский зелёный",
        "Oil Green" to "Масляно-зелёный",
        "Red" to "Красный",
        "Spectrum Red" to "Спектральный красный",
        "Dark Greenish Glaucous" to "Тёмный зеленовато-сизый",
        "Maple" to "Кленовый",
        "Eugenia Red | A" to "Красный «Евгения» A",
        "Artemesia Green" to "Полынно-зелёный",
        "Indian Lake" to "Индийский лак",
        "Light Pinkish Cinnamon" to "Светлый розовато-коричный",
        "Violet Carmine" to "Фиолетово-карминовый",
        "Dull Citrine" to "Приглушённый цитриновый",
        "Dark Perilla Purple" to "Тёмный периллово-пурпурный",
        "Pale Purplish Vinaceous" to "Светлый пурпурно-винный",
        "Grape Green" to "Виноградно-зелёный",
        "Pale Cinnamon-Pink" to "Светлый корично-розовый",
        "Sea-foam Yellow" to "Жёлтый морской пены",
        "Dull Purplish Black" to "Приглушённый пурпурно-чёрный",
        "Pale King's Blue 1" to "Бледный королевский синий 1",
        "Pale Ecru-Drab" to "Светлый экрю-серо-бежевый",
        "Pale Methyl Blue" to "Светлый метиловый синий",
        "Violet Ultramarine" to "Фиолетовый ультрамарин",
        "Pale Turtle Green" to "Светлый черепахово-зелёный"
    )

    fun of(english: String): String = names[english] ?: english
}
